### PR TITLE
Add section of readme for related resources/code/projects

### PR DESCRIPTION
**Pull request by patcon**
Lots of these are hard to track down, so hopefully listing them can give people inspiration or an idea of existing efforts that passionate people are/were working on :)

Not sure "deploy" feels like the right place, but it's the closest thing we have to a full "meta" repo. (polis-issues` feels much too transient, and `polis-documentation` is too official.)

### CODE REVIEW

**Comment by colinmegill** [comment]
@patcon Huge thank you for tracking these down. We are going to launch an upgraded docs.pol.is, and this deserves a section there.

**Comment by patcon** [comment]
No prob! Some of these might be very "dev"y and messy and unofficial, so as long as that won't make you feel pressure to leave things off, then I would totally agree that the doc site is an ok place.

But if some experimental things (that very interested ppl looking at the repo would still care to see) wouldn't make the cut into the front facing docs site, then i might suggest keeping the authoritative one here, and cherrypicking? :)

**Comment by patcon** [comment]
Also, yay for updated docs.pol.is! Lemme know if I can help or review anything

**Comment by colinmegill** [comment]
That would be most excellent!

**Comment by patcon** [comment]
Hey colin, is there a place I could add these, or worth merging? Otherwise, I can just close out, but would love to keep them somewhere if "good enough for now; safe enough to try" :)

**Comment by patcon** [comment]
Alternatively, I could start an [awesome-list](https://github.com/sindresorhus/awesome) and store this sorta stuff outside

**Comment by patcon** [comment]
one more! Mentioned here https://gitter.im/pol-is/polisDeployment?at=5e9d94c1a412254f219e79e5
https://github.com/Demos-thinktank/dynata-id

**Comment by patcon** [comment]
Closing this as part of repo transfer (https://github.com/pol-is/polis-issues/issues/134), but will cross-ref there so convo not lost.

**Pull request closed without merging**
